/*
  +------------------------------------------------------------------------+
  | Dao Framework                                                          |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2014 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  |          Vladimir Kolesnikov <vladimir@extrememember.com>              |
  |          ZhuZongXin <dreamsxin@qq.com>                                 |
  +------------------------------------------------------------------------+
*/

#include "php_dao.h"
#include "interned-strings.h"
#include "kernel/main.h"
#include "kernel/string.h"

zend_string *dao_interned_DELETE						= NULL;
zend_string *dao_interned_GET							= NULL;
zend_string *dao_interned_HEAD							= NULL;
zend_string *dao_interned_OPTIONS						= NULL;
zend_string *dao_interned_PATCH							= NULL;
zend_string *dao_interned_POST							= NULL;
zend_string *dao_interned_PUT							= NULL;
zend_string *dao_interned_default						= NULL;
zend_string *dao_interned_autoLoad						= NULL;
zend_string *dao_interned_di							= NULL;
zend_string *dao_interned_action						= NULL;
zend_string *dao_interned_alias							= NULL;
zend_string *dao_interned_all							= NULL;
zend_string *dao_interned_allowEmpty					= NULL;
zend_string *dao_interned_arguments						= NULL;
zend_string *dao_interned_balias						= NULL;
zend_string *dao_interned_binary_op						= NULL;
zend_string *dao_interned_code							= NULL;
zend_string *dao_interned_column						= NULL;
zend_string *dao_interned_columns						= NULL;
zend_string *dao_interned_conditions					= NULL;
zend_string *dao_interned_controller					= NULL;
zend_string *dao_interned_delete						= NULL;
zend_string *dao_interned_dispatcher					= NULL;
zend_string *dao_interned_distinct						= NULL;
zend_string *dao_interned_domain						= NULL;
zend_string *dao_interned_escaper						= NULL;
zend_string *dao_interned_expr							= NULL;
zend_string *dao_interned_fields						= NULL;
zend_string *dao_interned_file							= NULL;
zend_string *dao_interned_filter						= NULL;
zend_string *dao_interned_functionCall					= NULL;
zend_string *dao_interned_group							= NULL;
zend_string *dao_interned_groupBy						= NULL;
zend_string *dao_interned_having						= NULL;
zend_string *dao_interned_items							= NULL;
zend_string *dao_interned_joins							= NULL;
zend_string *dao_interned_label							= NULL;
zend_string *dao_interned_left							= NULL;
zend_string *dao_interned_limit							= NULL;
zend_string *dao_interned_forupdate						= NULL;
zend_string *dao_interned_line							= NULL;
zend_string *dao_interned_message						= NULL;
zend_string *dao_interned_model							= NULL;
zend_string *dao_interned_models						= NULL;
zend_string *dao_interned_modelsCache					= NULL;
zend_string *dao_interned_modelsManager					= NULL;
zend_string *dao_interned_modelsMetadata				= NULL;
zend_string *dao_interned_modelsQuery					= NULL;
zend_string *dao_interned_modelsQueryBuilderForSelect	= NULL;
zend_string *dao_interned_modelsQueryBuilderForInsert	= NULL;
zend_string *dao_interned_modelsQueryBuilderForUpdate	= NULL;
zend_string *dao_interned_modelsQueryBuilderForDelete	= NULL;
zend_string *dao_interned_modelsCriteria				= NULL;
zend_string *dao_interned_modelsResultsetSimple			= NULL;
zend_string *dao_interned_modelsResultsetComplex		= NULL;
zend_string *dao_interned_modelsRow						= NULL;
zend_string *dao_interned_module						= NULL;
zend_string *dao_interned_name							= NULL;
zend_string *dao_interned_namespace						= NULL;
zend_string *dao_interned_ns_alias						= NULL;
zend_string *dao_interned_number						= NULL;
zend_string *dao_interned_offset						= NULL;
zend_string *dao_interned_op							= NULL;
zend_string *dao_interned_order							= NULL;
zend_string *dao_interned_orderBy						= NULL;
zend_string *dao_interned_params						= NULL;
zend_string *dao_interned_parent						= NULL;
zend_string *dao_interned_paths							= NULL;
zend_string *dao_interned_qualified						= NULL;
zend_string *dao_interned_qualifiedName					= NULL;
zend_string *dao_interned_request						= NULL;
zend_string *dao_interned_response						= NULL;
zend_string *dao_interned_right							= NULL;
zend_string *dao_interned_router						= NULL;
zend_string *dao_interned_select						= NULL;
zend_string *dao_interned_self							= NULL;
zend_string *dao_interned_session						= NULL;
zend_string *dao_interned_sort							= NULL;
zend_string *dao_interned_source						= NULL;
zend_string *dao_interned_static						= NULL;
zend_string *dao_interned_sqlAlias						= NULL;
zend_string *dao_interned_table							= NULL;
zend_string *dao_interned_tables						= NULL;
zend_string *dao_interned_type							= NULL;
zend_string *dao_interned_update						= NULL;
zend_string *dao_interned_url							= NULL;
zend_string *dao_interned_value							= NULL;
zend_string *dao_interned_values						= NULL;
zend_string *dao_interned_where							= NULL;
zend_string *dao_interned_cookies						= NULL;
zend_string *dao_interned_annotations					= NULL;
zend_string *dao_interned_security						= NULL;
zend_string *dao_interned_crypt							= NULL;
zend_string *dao_interned_flash							= NULL;
zend_string *dao_interned_flashSession					= NULL;
zend_string *dao_interned_tag							= NULL;
zend_string *dao_interned_sessionBag					= NULL;
zend_string *dao_interned_eventsManager					= NULL;
zend_string *dao_interned_transactionManager			= NULL;
zend_string *dao_interned_assets						= NULL;
zend_string *dao_interned_rows							= NULL;
zend_string *dao_interned_db							= NULL;
zend_string *dao_interned_view							= NULL;
zend_string *dao_interned_php							= NULL;
zend_string *dao_interned_except						= NULL;
zend_string *dao_interned_app							= NULL;
zend_string *dao_interned_application					= NULL;
zend_string *dao_interned_validation					= NULL;
zend_string *dao_interned_translate						= NULL;
zend_string *dao_interned_logger						= NULL;

DAO_STATIC void dao_init_interned_strings()
{
	dao_interned_DELETE							= SSL("DELETE");
	dao_interned_GET							= SSL("GET");
	dao_interned_HEAD							= SSL("HEAD");
	dao_interned_OPTIONS						= SSL("OPTIONS");
	dao_interned_PATCH							= SSL("PATCH");
	dao_interned_POST							= SSL("POST");
	dao_interned_PUT							= SSL("PUT");
	dao_interned_default						= SSL("default");
	dao_interned_autoLoad						= SSL("autoLoad");
	dao_interned_di								= SSL("di");
	dao_interned_action							= SSL("action");
	dao_interned_alias							= SSL("alias");
	dao_interned_all							= SSL("all");
	dao_interned_allowEmpty						= SSL("allowEmpty");
	dao_interned_arguments						= SSL("arguments");
	dao_interned_balias							= SSL("balias");
	dao_interned_binary_op						= SSL("binary-op");
	dao_interned_code							= SSL("code");
	dao_interned_column							= SSL("column");
	dao_interned_columns						= SSL("columns");
	dao_interned_conditions						= SSL("conditions");
	dao_interned_controller						= SSL("controller");
	dao_interned_delete							= SSL("delete");
	dao_interned_dispatcher						= SSL("dispatcher");
	dao_interned_distinct						= SSL("distinct");
	dao_interned_domain							= SSL("domain");
	dao_interned_escaper						= SSL("escaper");
	dao_interned_expr							= SSL("expr");
	dao_interned_fields							= SSL("fields");
	dao_interned_file							= SSL("file");
	dao_interned_filter							= SSL("filter");
	dao_interned_functionCall					= SSL("functionCall");
	dao_interned_group							= SSL("group");
	dao_interned_groupBy						= SSL("groupBy");
	dao_interned_having							= SSL("having");
	dao_interned_items							= SSL("items");
	dao_interned_joins							= SSL("joins");
	dao_interned_label							= SSL("label");
	dao_interned_left							= SSL("left");
	dao_interned_limit							= SSL("limit");
	dao_interned_forupdate						= SSL("forupdate");
	dao_interned_line							= SSL("line");
	dao_interned_message						= SSL("message");
	dao_interned_model							= SSL("model");
	dao_interned_models							= SSL("models");
	dao_interned_modelsCache					= SSL("modelsCache");
	dao_interned_modelsManager					= SSL("modelsManager");
	dao_interned_modelsMetadata					= SSL("modelsMetadata");
	dao_interned_modelsQuery					= SSL("modelsQuery");
	dao_interned_modelsQueryBuilderForSelect	= SSL("modelsQueryBuilderForSelect");
	dao_interned_modelsQueryBuilderForInsert	= SSL("modelsQueryBuilderForInsert");
	dao_interned_modelsQueryBuilderForUpdate	= SSL("modelsQueryBuilderForUpdate");
	dao_interned_modelsQueryBuilderForDelete	= SSL("modelsQueryBuilderForDelete");
	dao_interned_modelsCriteria					= SSL("modelsCriteria");
	dao_interned_modelsResultsetSimple			= SSL("modelsResultsetSimple");
	dao_interned_modelsResultsetComplex			= SSL("modelsResultsetComplex");
	dao_interned_modelsRow						= SSL("modelsRow");
	dao_interned_module							= SSL("module");
	dao_interned_name							= SSL("name");
	dao_interned_namespace						= SSL("namespace");
	dao_interned_ns_alias						= SSL("ns-alias");
	dao_interned_number							= SSL("number");
	dao_interned_offset							= SSL("offset");
	dao_interned_op								= SSL("op");
	dao_interned_order							= SSL("order");
	dao_interned_orderBy						= SSL("orderBy");
	dao_interned_params							= SSL("params");
	dao_interned_parent							= SSL("parent");
	dao_interned_paths							= SSL("paths");
	dao_interned_qualified						= SSL("qualified");
	dao_interned_qualifiedName					= SSL("qualifiedName");
	dao_interned_request						= SSL("request");
	dao_interned_response						= SSL("response");
	dao_interned_right							= SSL("right");
	dao_interned_router							= SSL("router");
	dao_interned_select							= SSL("select");
	dao_interned_self							= SSL("self");
	dao_interned_session						= SSL("session");
	dao_interned_sort							= SSL("sort");
	dao_interned_source							= SSL("source");
	dao_interned_static							= SSL("static");
	dao_interned_sqlAlias						= SSL("sqlAlias");
	dao_interned_table							= SSL("table");
	dao_interned_tables							= SSL("tables");
	dao_interned_type							= SSL("type");
	dao_interned_update							= SSL("update");
	dao_interned_url							= SSL("url");
	dao_interned_value							= SSL("value");
	dao_interned_values							= SSL("values");
	dao_interned_where							= SSL("where");
	dao_interned_rows							= SSL("rows");
	dao_interned_cookies						= SSL("cookies");
	dao_interned_annotations					= SSL("annotations");
	dao_interned_security						= SSL("security");
	dao_interned_crypt							= SSL("crypt");
	dao_interned_flash							= SSL("flash");
	dao_interned_flashSession					= SSL("flashSession");
	dao_interned_tag							= SSL("tag");
	dao_interned_sessionBag						= SSL("sessionBag");
	dao_interned_eventsManager					= SSL("eventsManager");
	dao_interned_transactionManager				= SSL("transactions");
	dao_interned_assets							= SSL("assets");
	dao_interned_db								= SSL("db");
	dao_interned_view							= SSL("view");
	dao_interned_php							= SSL("php");
	dao_interned_except							= SSL("except");
	dao_interned_app							= SSL("app");
	dao_interned_application					= SSL("application");
	dao_interned_validation						= SSL("validation");
	dao_interned_translate						= SSL("translate");
	dao_interned_logger							= SSL("logger");
}

DAO_STATIC void dao_release_interned_strings()
{
	zend_string_release(dao_interned_DELETE);
	zend_string_release(dao_interned_GET);
	zend_string_release(dao_interned_HEAD);
	zend_string_release(dao_interned_OPTIONS);
	zend_string_release(dao_interned_PATCH);
	zend_string_release(dao_interned_POST);
	zend_string_release(dao_interned_PUT);
	zend_string_release(dao_interned_default);
	zend_string_release(dao_interned_autoLoad);
	zend_string_release(dao_interned_di);
	zend_string_release(dao_interned_action);
	zend_string_release(dao_interned_alias);
	zend_string_release(dao_interned_all);
	zend_string_release(dao_interned_allowEmpty);
	zend_string_release(dao_interned_arguments);
	zend_string_release(dao_interned_balias);
	zend_string_release(dao_interned_binary_op);
	zend_string_release(dao_interned_code);
	zend_string_release(dao_interned_column);
	zend_string_release(dao_interned_columns);
	zend_string_release(dao_interned_conditions);
	zend_string_release(dao_interned_controller);
	zend_string_release(dao_interned_delete);
	zend_string_release(dao_interned_dispatcher);
	zend_string_release(dao_interned_distinct);
	zend_string_release(dao_interned_domain);
	zend_string_release(dao_interned_escaper);
	zend_string_release(dao_interned_expr);
	zend_string_release(dao_interned_fields);
	zend_string_release(dao_interned_file);
	zend_string_release(dao_interned_filter);
	zend_string_release(dao_interned_functionCall);
	zend_string_release(dao_interned_group);
	zend_string_release(dao_interned_groupBy);
	zend_string_release(dao_interned_having);
	zend_string_release(dao_interned_items);
	zend_string_release(dao_interned_joins);
	zend_string_release(dao_interned_label);
	zend_string_release(dao_interned_left);
	zend_string_release(dao_interned_limit);
	zend_string_release(dao_interned_forupdate);
	zend_string_release(dao_interned_line);
	zend_string_release(dao_interned_message);
	zend_string_release(dao_interned_model);
	zend_string_release(dao_interned_models);
	zend_string_release(dao_interned_modelsCache);
	zend_string_release(dao_interned_modelsManager);
	zend_string_release(dao_interned_modelsMetadata);
	zend_string_release(dao_interned_modelsQuery);
	zend_string_release(dao_interned_modelsQueryBuilderForSelect);
	zend_string_release(dao_interned_modelsQueryBuilderForInsert);
	zend_string_release(dao_interned_modelsQueryBuilderForUpdate);
	zend_string_release(dao_interned_modelsQueryBuilderForDelete);
	zend_string_release(dao_interned_modelsCriteria);
	zend_string_release(dao_interned_modelsResultsetSimple);
	zend_string_release(dao_interned_modelsResultsetComplex);
	zend_string_release(dao_interned_modelsRow);
	zend_string_release(dao_interned_module);
	zend_string_release(dao_interned_name);
	zend_string_release(dao_interned_namespace);
	zend_string_release(dao_interned_ns_alias);
	zend_string_release(dao_interned_number);
	zend_string_release(dao_interned_offset);
	zend_string_release(dao_interned_op);
	zend_string_release(dao_interned_order);
	zend_string_release(dao_interned_orderBy);
	zend_string_release(dao_interned_params);
	zend_string_release(dao_interned_parent);
	zend_string_release(dao_interned_paths);
	zend_string_release(dao_interned_qualified);
	zend_string_release(dao_interned_qualifiedName);
	zend_string_release(dao_interned_request);
	zend_string_release(dao_interned_response);
	zend_string_release(dao_interned_right);
	zend_string_release(dao_interned_router);
	zend_string_release(dao_interned_select);
	zend_string_release(dao_interned_self);
	zend_string_release(dao_interned_session);
	zend_string_release(dao_interned_sort);
	zend_string_release(dao_interned_source);
	zend_string_release(dao_interned_static);
	zend_string_release(dao_interned_sqlAlias);
	zend_string_release(dao_interned_table);
	zend_string_release(dao_interned_tables);
	zend_string_release(dao_interned_type);
	zend_string_release(dao_interned_update);
	zend_string_release(dao_interned_url);
	zend_string_release(dao_interned_value);
	zend_string_release(dao_interned_values);
	zend_string_release(dao_interned_where);
	zend_string_release(dao_interned_rows);
	zend_string_release(dao_interned_cookies);
	zend_string_release(dao_interned_annotations);
	zend_string_release(dao_interned_security);
	zend_string_release(dao_interned_crypt);
	zend_string_release(dao_interned_flash);
	zend_string_release(dao_interned_flashSession);
	zend_string_release(dao_interned_tag);
	zend_string_release(dao_interned_sessionBag);
	zend_string_release(dao_interned_eventsManager);
	zend_string_release(dao_interned_transactionManager);
	zend_string_release(dao_interned_assets);
	zend_string_release(dao_interned_db);
	zend_string_release(dao_interned_view);
	zend_string_release(dao_interned_php);
	zend_string_release(dao_interned_except);
	zend_string_release(dao_interned_app);
	zend_string_release(dao_interned_application);
	zend_string_release(dao_interned_validation);
	zend_string_release(dao_interned_translate);
	zend_string_release(dao_interned_logger);
}
