<?php 

namespace Dao {

	/**
	 * Dao\Snowflake
	 *
	 *<code>
	 *  $snowflake = new Dao\Snowflake;
	 *  $id = $snowflake->nextId();
	 *  $desc = $snowflake->parse($id);
	 *</code>
	 */
	
	class Snowflake {

		/**
		 * Returns a unique id value generated by the snowflake
		 *
		 *<code>
		 *  $snowflake = new \Dao\Snowflake;
		 *  $id = $snowflake->nextId();
		 *</code>
		 */
		public function nextId(){ }


		/**
		 * Parse a unique id value
		 *
		 *<code>
		 *  $snowflake = new \Dao\Snowflake;
		 *  $desc = $snowflake->parse($id);
		 *</code>
		 */
		public function parse($id){ }


		/**
		 * Parse a unique id value
		 *
		 *<code>
		 *  $desc = \Dao\Snowflake::parseID($id);
		 *</code>
		 */
		public static function parseID($id){ }

	}
}
